SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MeetingDetails](
	[MeetingID] [int] IDENTITY(1,1) NOT NULL,
	[MeetingSubject] [nvarchar](50) NOT NULL,
	[MeetingAgenda] [nvarchar](max) NULL,
	[MeetingTime] [nvarchar](50) NOT NULL,
	[MeetingAttendees] [nvarchar](max) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[MeetingDetails] ADD PRIMARY KEY CLUSTERED 
(
	[MeetingID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
